# Generated by Django 4.2.4 on 2023-10-31 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_pricerange_alter_item_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricerange',
            name='name',
            field=models.CharField(max_length=6),
        ),
    ]
