# Generated by Django 4.2.4 on 2023-10-31 12:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0005_alter_pricerange_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(10000, message='Price must be at least 5 digits'), django.core.validators.MaxValueValidator(99999, message='Price cannot exceed 5 digits')]),
        ),
    ]
