# Generated by Django 4.2.4 on 2023-10-11 10:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profile', '0005_profile_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFontChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('font_choice', models.CharField(choices=[('font1', 'Font Choice 1'), ('font2', 'Font Choice 2'), ('font3', 'Font Choice 3')], default='Arial', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
