# Generated by Django 4.2.4 on 2023-10-11 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0006_userfontchoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Font',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('font_file', models.FileField(upload_to='fonts/')),
            ],
        ),
        migrations.DeleteModel(
            name='UserFontChoice',
        ),
    ]
