# Generated by Django 4.2.4 on 2023-10-11 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0008_profile_selected_font'),
    ]

    operations = [
        migrations.AlterField(
            model_name='font',
            name='font_file',
            field=models.FileField(blank=True, null=True, upload_to='profile_fonts/'),
        ),
    ]
